### ISSUE TITLE
Bug on Ubuntu 19.04

### ISSUE THREAD

**Issue by vrossum** [kernc/xsuspender#14]
On Ubuntu 19.04, I get:
"(xsuspender:15598): GLib-WARNING **: 14:29:02.244: GError set over the top of a previous GError or uninitialized memory.
This indicates a bug in someone's code. You must ensure an error is NULL before it's set.
The overwriting error message was: Failed to open file ?/sys/class/power_supply/BAT0/online?: No such file or directory"

THere is no 
/sys/class/power_supply/BAT0/online
there is however
/sys/class/power_supply/AC/online

**Comment by kernc** [comment]
Thanks. IIUC, `err` should be reset to `NULL` in each `while` loop iteration before this line:
https://github.com/kernc/xsuspender/blob/4e4497042c65a0127d83b3d9b324cf61a67d70cd/src/events.c#L229

**Comment by vrossum** [comment]
So how to do that?

(PS your thumbnail looks like a swastika!)

**Comment by vrossum** [comment]
Ok this works:
-const char *DIRNAME = "/sys/class/power_supply";
+const char *DIRNAME = "/sys/class/power_supply/AC";

-g_autofree char *filename = g_build_filename (DIRNAME, basename, "online", NULL);
+g_autofree char *filename = g_build_filename (DIRNAME, "online", NULL);

**Comment by vrossum** [comment]
This works: 
(only check 
sys/class/power_supply/AC/online)



static
gboolean
is_on_ac_power ()
{
#ifdef __linux__
    // Read AC power state from /sys/class/power_supply/AC/online (== 1 on AC).
    // Should work in most cases. See: https://bugs.debian.org/473629

    const char *DIRNAME = "/sys/class/power_supply/AC";
    g_autoptr (GError) err = NULL;

	g_autofree char *filename = g_build_filename (DIRNAME, "online", NULL);
	g_autofree char *contents = NULL;

	g_debug ("Reading '%s'", filename);
	if (! g_file_get_contents (filename, &contents, NULL, &err)) {
	    g_debug ("Cannot read '%s': %s", filename, err->message);
	}

	if (g_strcmp0 (g_strstrip (contents), "1") == 0)
	    return TRUE;
    
    #warning "No battery / AC status support for your platform."
    #warning "Defaulting to as if 'always on battery' behavior. Patches welcome!"
    return FALSE;

#elif defined(__unix__) && defined(BSD) && !defined(__APPLE__)
    // On *BSD, run `apm -a` which returns '1' when AC is online
    g_autoptr (GError) err = NULL;
    g_autofree char *standard_output = NULL;
    char *argv[] = {"apm", "-a", NULL};

    g_spawn_sync (NULL, argv, NULL, G_SPAWN_SEARCH_PATH | G_SPAWN_STDERR_TO_DEV_NULL,
                  NULL, NULL, &standard_output, NULL, NULL, &err);
    if (err)
        g_warning ("Unexpected `apm -a` execution error: %s", err->message);

    return standard_output && 0 == g_strcmp0 (g_strstrip (standard_output), "1");
#endif
}

**Comment by smeijer** [comment]
I'm having a similar error on `19.10`. When running xsuspender in debug mode, I'm seeing this log over and over:

> Reading '/sys/class/power_supply/AC/online'
> Reading '/sys/class/power_supply/BAT0/online'
> Cannot read '/sys/class/power_supply/BAT0/online': Failed to open file ?/sys/class/power_supply/BAT0/online?: No such file or directory
