### ISSUE TITLE
Create AUR Pkg

### ISSUE THREAD

**Issue by skast96** [kernc/xsuspender#16]
Would be nice to have an AUR Pkg

**Comment by kernc** [comment]
I think that package would be best maintained by someone using Arch Linux ...

https://wiki.archlinux.org/index.php/Creating_packages

**Comment by stewi1014** [comment]
I've put together a PKGBUILD which seems to work.

`
# This is the search path for xsuspender's config file.
# Unfortunately I don't think it's reasonable or good to create it here,
# so we leave it up to the user to create. The package will do nothing unless it is created.
# An example config resides in /usr/share/doc/xsuspender/examples/xsuspender.conf
#CONFIG_FILE=xsuspender.conf
#if [ -z "$XDG_CONFIG_HOME"]; then
#    CONFIG_PATH=$XDG_CONFIG_HOME/$CONFIG_FILE
#else
#    CONFIG_PATH=~/.config/$CONFIG_FILE
#fi

pkgname=xsuspender-git
pkgver=0.0.0
pkgrel=1
pkgdesc="Automatically suspend inactive X11 applications."
arch=('i686' 'x86_64')
url="https://github.com/kernc/xsuspender"
license=('WTFPL')
depends=('glib2' 'libwnck3')
makedepends=('git' 'cmake' 'make')
source=("$pkgname"::'git+https://github.com/kernc/xsuspender.git#branch=master')
md5sums=('SKIP')

pkgver() { 
    cd "$srcdir/$pkgname"
    git describe --long --tags | sed -E 's/([^-]*-g)/r\1/;s/-/./g'
}

build() {
    cd "$srcdir/$pkgname"
    cmake -DCMAKE_INSTALL_PREFIX=/usr .
    make
    make test
}

package() {
    cd "$srcdir/$pkgname"
    make DESTDIR="$pkgdir/" install
    
    cd $pkgdir
    
    mkdir etc
    mv usr/etc/* etc/
    rm -rf usr/etc
}
`

I always appreciate when packages give me a helpful default/commented out config to modify, but the guys on the IRC channel inform me, and I don't disagree, that build scripts should never touch anything to do with the user, so the config being in home poses an issue. There's no guarantee the same user building the package is the same one that will run it, nor them even using the same computer. I'd be interested to hear what you do on Debian; copying it is probably best.

So I'm completely relying on the user to manually create the configuration file in ~/.config or $XDG_CONFIG_HOME. I'll continue looking into this.

**Comment by stewi1014** [comment]
I went ahead and published it to the AUR @skast96 
https://aur.archlinux.org/packages/xsuspender-git/

**Comment by kernc** [comment]
xsuspender reads `${XDG_CONFIG_HOME:-~/.config}/xsuspender.conf` (_and this file alone_) via this line:
https://github.com/kernc/xsuspender/blob/ee088d8b8eab2124b5af8528e8536747950e8188/src/config.c#L239
so I don't think `CONFIG_PATH` lines in your PKGBUILD do anything?

Debian packages, similarly, write only default config files _outside user's home_. But this project, so far, has _no default configuration_, rather just an example (I view it as a matter of responsibility :grin:). This might change once the example is expanded to cover more apps. For the time being, the user will need to copy the example on their own. I feel like the awareness for the file is raised somewhat sufficiently:
https://github.com/kernc/xsuspender/blob/ee088d8b8eab2124b5af8528e8536747950e8188/src/config.c#L242-L243
https://github.com/kernc/xsuspender/blob/ee088d8b8eab2124b5af8528e8536747950e8188/src/xsuspender.c#L246-L249
https://github.com/kernc/xsuspender/blob/92c6b246f1361e9a78d597edeab45fb2314f28f4/doc/xsuspender.1#L101-L110

Re `Hidden=True`, this is what _disabled_ here refers to:
https://github.com/kernc/xsuspender/blob/ee088d8b8eab2124b5af8528e8536747950e8188/doc/xsuspender.1#L112-L121
The file is installed for any X11 desktop session autostart, but I simply don't want the program to really start without the (each) user's explicit approval.



> I'm getting a warning that a reference to the (temporary) source directory used during compile exists in the compiled executable. The string causing the warning is "/home/stewi/xsuspender/src/xsuspender-git/src/exec.c" for me. Do you know what might be including it during compile? No such reference exists for other source files.

No idea what's causing the warning. Likely has something to do with compilation. For me, a reference to source dir seems to be present in every file:
```bash
$ strings -f src/CMakeFiles/xsuspender.dir/*.c.o | grep xsuspender/src$

src/CMakeFiles/xsuspender.dir/config.c.o: /home/user/xsuspender/src
src/CMakeFiles/xsuspender.dir/entry.c.o: /home/user/xsuspender/src
src/CMakeFiles/xsuspender.dir/events.c.o: /home/user/xsuspender/src
src/CMakeFiles/xsuspender.dir/exec.c.o: /home/user/xsuspender/src
src/CMakeFiles/xsuspender.dir/rule.c.o: /home/user/xsuspender/src
src/CMakeFiles/xsuspender.dir/xsuspender.c.o: /home/user/xsuspender/src
```

**Comment by kernc** [comment]
@stewi1014 Mind also PRing an [Arch link for the readme](https://github.com/kernc/xsuspender#binary-packages)? :smiley:

**Comment by stewi1014** [comment]
Thanks so much for the info. I think that answers everything I wanted to know.

I briefly considered copying the example config into CONFIG_PATH in the PKGBUILD, but quickly realised it was a terrible idea. I think you're absolutely right; there's no sensible default config, and with no sensible default config, it doesn't make sense to have autostart enabled by default. And like you said, it is well documented.

I think the PKGBUILD currently in the AUR reflects all of this, so great!

I'll add it to README :)
