### ISSUE TITLE
libwnck not found in OpenSuSE Leap 15.2

### ISSUE THREAD

**Issue by jlturriff** [kernc/xsuspender#25]
I'm trying to install Xsuspender in my OpenSuSE Leap 15.2 (an RPM-based) desktop system.  When I run
`cmake -DCMAKE_INSTALL_PREFIX=/usr/local ..`
I get the following output:

`$ cmake -DCMAKE_INSTALL_PREFIX=/usr/local ..
-- The C compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2")
-- Checking for module 'glib-2.0'
--   Found glib-2.0, version 2.62.6
-- Checking for module 'libwnck-3.0'
**--   No package 'libwnck-3.0' found**
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:467 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:647 (_pkg_check_modules_internal)
  src/CMakeLists.txt:4 (pkg_check_modules)

-- Configuring incomplete, errors occurred!
See also "/usr/local/Downloads/Packages/Non-RPMs/Linux/xsuspender-master/build/CMakeFiles/CMakeOutput.log".`

Searching my system, I see that libwnck-3 is installed, but its name is different:

`$ rpm -q libwnck-3-0 --filesbypkg

libwnck-3-0               **/usr/lib64/libwnck-3.so.0**

libwnck-3-0               **/usr/lib64/libwnck-3.so.0.3.0**

libwnck-3-0               /usr/share/doc/packages/libwnck-3-0

libwnck-3-0               /usr/share/doc/packages/libwnck-3-0/AUTHORS

libwnck-3-0               /usr/share/doc/packages/libwnck-3-0/ChangeLog

libwnck-3-0               /usr/share/doc/packages/libwnck-3-0/NEWS

libwnck-3-0               /usr/share/doc/packages/libwnck-3-0/README

libwnck-3-0               /usr/share/licenses/libwnck-3-0

libwnck-3-0               /usr/share/licenses/libwnck-3-0/COPYING`

Can I get past this by making a symbolic link that cmake will recognize, or is there some better/more correct way to handle it?

**Comment by kernc** [comment]
Did you [install package _libwnck-devel_](https://github.com/kernc/xsuspender#from-source)? You need libwnck _source code_ to compile the project, then the build lib (*.so) for running.

**Comment by jlturriff** [comment]
Oh, gosh.  Sorry to bother you.

Leslie

On 2021-02-09 15:23:13 kernc wrote:
> Did you [install package
> _libwnck-devel_](https://github.com/kernc/xsuspender#from-source)? You need
> libwnck _source code_ to compile the project, then the build lib (*.so) for
> running.


--
