### ISSUE TITLE
Mouse battery messing it up?

### ISSUE THREAD

**Issue by m0ngr31** [kernc/xsuspender#29]
Just trying it out and it seems to work pretty good for my use case, but when I plug in the dongle for my wireless mouse, I get an error:

```
Message from syslogd@fightgar at Oct 29 08:47:22 ...
 kernel:[ 4108.289786] Uhhuh. NMI received for unknown reason 30 on CPU 0.

Message from syslogd@fightgar at Oct 29 08:47:22 ...
 kernel:[ 4108.289787] Do you have a strange power saving mode enabled?```

Any way I can tell it to ignore the mouse battery?

**Comment by kernc** [comment]
I don't think those comments have anything to do with xsuspender. The only place we poll battery state is this:
https://github.com/kernc/xsuspender/blob/d96510f61c28c002c092b2c7a9edc6df6162f1d6/src/events.c#L206-L254
