### ISSUE TITLE
Suspend process tree without using external dependencies

### ISSUE THREAD

**Issue by offlinehacker** [kernc/xsuspender#3]
## Issue description

Currently `procps`, `gawk`, `coreutils`, `bash` and `findutils` are needed to run a script that suspends whole process tree. This not only presents extra unneeded dependencies, but also slows downs execution as not only `xsuspender`, but also executed bash process needs to execute other processes. Also user needs to have these tools installed and in path, except if wrapper is made around installed `xsuspender` binary, like it is on nixos ;)

## Solution

Implement process tree parsing in native `C`. While these requires a few extra lines of code, it makes `xsuspender` even more portable as it is.

**Comment by kernc** [comment]
:+1: 

I'll accept walking of /proc/*/ and comparing cmdline with glib's regexes.

https://developer.gnome.org/glib/stable/glib-Perl-compatible-regular-expressions.html

**Comment by kernc** [comment]
How does https://github.com/kernc/xsuspender/pull/9 look?
