### ISSUE TITLE
Better config examples

### ISSUE THREAD

**Issue by fastjack77** [kernc/xsuspender#31]
Greetings from the Internet,

Would it be possible to have more detailed config examples for the intellectually disabled pleb (e.g. me).

Thank you!

**Comment by kernc** [comment]
More detailed config examples besides the [default config](https://github.com/kernc/xsuspender/blob/93134ca965e4f5ec208fbd4ddf6cf10667e5b1e9/data/xsuspender.conf) that ships with the software and [the manual](https://kernc.github.io/xsuspender/xsuspender.1.html) that covers it? :grimacing: :thinking:
