### ISSUE TITLE
downclock_on_battery=0 🤔

### ISSUE THREAD

**Issue by jothi-prasath** [kernc/xsuspender#41]
`downclock_on_battery ` I know 1 is 50% , 2 is 66% but what about zero

**Comment by kernc** [comment]
Simply. if `downclock_on_battery = 0`, the matching process is not downclocked:
https://github.com/kernc/xsuspender/blob/15ab5563345f5c7fa2674112faf56ab4a30f2bfb/src/events.c#L407-L414
